# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

# Optionally build your docs in additional formats such as PDF
formats:
  - htmlzip
  - pdf

# Build documentation in the "latest", "stable", and all tags
build:
  os: ubuntu-22.04
  tools:
    python: "3.8"
  commands:
    - pip install --upgrade pip
    - pip install -r docs/requirements.txt
    - pip install -e .
    - sphinx-build -b html docs docs/_build/html
