# SparkForge Security Configuration
# This file defines security policies and configurations for SparkForge

# Security scanning configuration
security_scanning:
  bandit:
    enabled: true
    severity_threshold: "medium"
    confidence_threshold: "medium"
    exclude_dirs:
      - "tests"
      - "build"
      - "dist"
      - ".venv"
      - "venv"
      - "htmlcov"
    skip_tests:
      - "B101"  # assert_used
      - "B601"  # shell=True
    output_format: "json"
    output_file: "bandit-report.json"
  
  safety:
    enabled: true
    check_requirements: true
    output_format: "json"
    output_file: "safety-report.json"
  
  dependency_scanning:
    enabled: true
    check_outdated: true
    check_vulnerabilities: true
    check_licenses: true
    output_format: "json"
    output_file: "dependency-report.json"

# Security monitoring configuration
security_monitoring:
  enabled: true
  monitoring_interval: 60  # seconds
  retention_days: 30
  alert_threshold: 10
  
  real_time_monitoring:
    enabled: true
    monitor_system_resources: true
    monitor_network_activity: true
    monitor_file_system: true
    monitor_process_activity: true
  
  anomaly_detection:
    enabled: true
    max_failed_auth_attempts: 5
    max_suspicious_requests: 10
    max_data_access_violations: 3
    max_privilege_escalation_attempts: 2
  
  rate_limiting:
    events_per_minute: 100
    alerts_per_hour: 50

# Compliance configuration
compliance:
  owasp_top_10:
    enabled: true
    compliance_threshold: 90  # percentage
  
  cve_compliance:
    enabled: true
    compliance_threshold: 95  # percentage
    check_dependencies: true
    check_runtime: true
  
  license_compliance:
    enabled: true
    compliance_threshold: 80  # percentage
    check_compatibility: true
    check_documentation: true
    check_copyleft: true
  
  security_best_practices:
    enabled: true
    compliance_threshold: 80  # percentage
    check_input_validation: true
    check_output_encoding: true
    check_error_handling: true
    check_logging_practices: true
    check_cryptographic_practices: true

# Security policies
security_policies:
  input_validation:
    required: true
    sanitization_required: true
    max_input_length: 10000
  
  output_encoding:
    required: true
    prevent_xss: true
    encode_special_chars: true
  
  error_handling:
    secure_error_messages: true
    log_errors: true
    prevent_information_disclosure: true
  
  authentication:
    required: false  # Framework level - should be implemented at application level
    session_management: false
    password_policy: false
  
  authorization:
    required: false  # Framework level - should be implemented at application level
    role_based_access: false
    permission_checks: false
  
  data_encryption:
    in_transit: true  # Should be implemented at infrastructure level
    at_rest: true     # Should be implemented at infrastructure level
    key_management: false  # Should be implemented at infrastructure level

# Security thresholds
security_thresholds:
  vulnerability_scan:
    max_high_severity: 0
    max_medium_severity: 5
    max_low_severity: 20
  
  compliance_check:
    min_owasp_score: 90
    min_cve_compliance: 95
    min_license_compliance: 80
    min_best_practices_score: 80
  
  performance_impact:
    max_scan_time: 300  # seconds
    max_memory_usage: 1024  # MB
    max_cpu_usage: 80  # percentage

# Security reporting
security_reporting:
  enabled: true
  output_formats:
    - "json"
    - "html"
    - "pdf"
  
  report_sections:
    - "executive_summary"
    - "vulnerability_scan"
    - "compliance_check"
    - "security_metrics"
    - "recommendations"
  
  automated_reports:
    enabled: true
    schedule: "daily"
    recipients: []
    email_notifications: false

# Integration configuration
integrations:
  ci_cd:
    enabled: true
    fail_on_high_severity: true
    fail_on_compliance_failure: true
    generate_reports: true
  
  monitoring_systems:
    prometheus:
      enabled: false
      endpoint: "http://localhost:9090"
    
    grafana:
      enabled: false
      endpoint: "http://localhost:3000"
    
    elasticsearch:
      enabled: false
      endpoint: "http://localhost:9200"
  
  notification_systems:
    slack:
      enabled: false
      webhook_url: ""
      channel: "#security"
    
    email:
      enabled: false
      smtp_server: ""
      smtp_port: 587
      username: ""
      password: ""
      recipients: []

# Development security
development_security:
  pre_commit_hooks:
    enabled: true
    security_scan: true
    license_check: true
  
  code_review:
    security_review_required: true
    security_expert_approval: false
  
  testing:
    security_tests_required: true
    penetration_testing: false
    vulnerability_assessment: true

# Production security
production_security:
  monitoring:
    real_time_monitoring: true
    alerting: true
    incident_response: true
  
  access_control:
    network_segmentation: true
    firewall_rules: true
    vpn_access: true
  
  backup_security:
    encrypted_backups: true
    secure_storage: true
    access_logging: true
  
  incident_response:
    automated_response: false
    escalation_procedures: true
    forensic_capabilities: true
